(function(z){
var KK=function(a,b,c){b="new"===(b||a.jd);return c?(a=a.d.u.v().get(z.U.hp),b?-1:-a):a.Ok+(b?-1:1)};var LK=function(a){z.zv.call(this,a);this.Ok=0;this.jd="new"};var MK=function(a,b){a.gW=b};var NK=function(a){return a.get(a.k.op)};
var OK=function(a){return(0,z.P)('\x3cdiv class\x3d"fyre '+(a.fe?"fyre-liveblog ":"")+(a.Xg?"fyre-livechat ":"")+(a.KS?"fyre-bootstrap ":"")+(a.ge?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Ua?"fyre-avatar-disabled":"")+'"\x3e'+(a.Uu?z.im(z.Fs(a)):"")+(0,z.P)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Ua?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.Tn?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var PK=function(a){return(0,z.P)('\x3ca href\x3d"'+z.Q(z.R(a.Da))+'" title\x3d"'+z.Q(a.Z)+'" data-id\x3d"'+z.Q(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.Q(a.tS)+'"\x3e\x3cimg src\x3d"'+z.Q(z.R(a.ud))+'" alt\x3d"'+z.Q(a.Z)+'" onerror\x3d"javascript:this.src\x3d\''+z.Q(z.Cm(a.Yb))+"';\" /\x3e\x3c/a\x3e")};
var QK=function(a){return(0,z.P)(z.Qq(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.O(a.j.XM)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(a.j.sx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(a.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(a.j.tx)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var RK=function(a){return(0,z.P)('\x3cdiv class\x3d"tooltip"\x3e'+z.O(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var SK=function(){};var TK=function(a){z.Gf.call(this,a);this.RI=new z.Pe({url:[z.w.K.dW,"stats"].join("/"),method:"POST",with_credentials:!1});this.vs=[];this.Bc=z.u.setInterval((0,z.t)(this.jy,this),5E3)};var UK=function(a){return z.Oa(a,function(a){return a.rate?Math.random()<a.rate:!0})};
var VK=function(a){var b={},c=z.Oa(a,function(a){if("counter"!==a.type)return!0;a.metric in b?b[a.metric].value+=a.value:b[a.metric]=a;return!1});z.y(b,function(a){c.push(a)});return c};var WK=function(a,b){z.Ej.call(this,b,a)};var XK=function(a,b){z.BF.call(this,a,b)};var YK=function(a,b){var c=a.d.Fb;c.kh[4]&&(z.Oy(c,4,(0,z.t)(function(a){b.e(a,"threadBreakout",this.mr)},a)),z.Qy(c,4,(0,z.t)(function(a){b.Za(a,"threadBreakout",this.mr)})))};
var ZK=function(a,b){var c=[a.Yl,a.Jy];a.rg&&c.push(a.rg);a.Ps&&c.push(a.Ps);a.Ky&&c.push(a.Ky);z.x(c,function(a){z.Io(a,"fyre-stream-sort-selected")});z.Go(b,"fyre-stream-sort-selected")};var $K=function(a,b){z.BF.call(this,a,b)};var aL=function(a,b){z.rx.call(this,a,b);this.Wg=!1;this.LH=!!this.J.M.LF;this.Fa=new z.zx;this.Fa.pc(this);this.Kt="archiveShowMore"};var bL=function(a,b){z.yF.call(this,a,b)};var cL=function(a,b,c){z.Tt.call(this,a,b,c);this.dz=b||"";this.og(RK(this.s()))};
var dL=function(a,b,c){z.Nt.call(this,a,b||3,c)};var eL=function(a,b){z.T.call(this,b);this.m=a};var fL=function(a,b){z.T.call(this,b);this.bc=a};var gL=function(a,b){fL.call(this,a,b)};
var hL=function(){var a=z.u.window,b=z.u.document;function c(){var a=C.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){C.MV||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(C,g)}function f(a){var b;if(a.eO)return a;if(C.LV&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.eO=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.ES&&a.ES("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var C={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.LV,shivMethods:!1!==g.MV,type:"default",shivDocument:f};f(b)};var iL=function(a,b){z.JF.call(this,a,b);a.M.YN||hL();var c=a.u.Lb(),d=a.u.v();this.fg=new z.zF(a,c,a.Bl.Ca,d.Xg()||z.cg);this.D(this.fg);a.M.Ua||(this.mn=new gL(c),this.D(this.mn));this.tr=new z.xF;this.D(this.tr)};var jL=function(a){var b=z.E.cb();return!a.B.fe()||b};var kL=function(a){z.Uy.call(this,a);this.Fm=1};var lL=function(a){z.Is.call(this,a);z.bv(a.u);this.Pb=new iL(a);this.Aq.start();this.pl(this.Pb);z.Ms(this)};
var mL=function(a,b){this.qC=WK;this.LI=lL;z.X.Do(b.strings||{});z.tl.call(this,a,b)};var nL=function(a){a.ek&&(a.ek.p(),delete a.ek)};z.v(LK,z.zv);z.e=LK.prototype;z.e.al=z.l(58);z.e.LE=z.l(60);z.e.ME=z.l(59);z.e.LE=z.K(60,function(a){this.Ia||(this.io[a]=!1,z.Av(this,a,function(a){a.N(a.xa.Em)}))});
z.e.ME=z.K(59,function(a,b){if(!this.Ia){var c=this.d.u.v(),d=z.yu(a,b),f=c.get(z.U.it);c.set(z.U.hp,d.VT);z.y(d.ab,(0,z.t)(this.d.T.N,this.d.T,"bootstrap_author_received"));d.content=z.hj(d.content,function(a,b){return!z.Ta(f,b)});z.y(d.content,function(a){z.kb(d.content,z.Cv(this,a))},this);z.kb(this.Cc,z.gj(d.content,z.Cb(a)));this.Td(a,d.content);z.Av(this,a,function(b){b.N(b.xa.sk,{Ed:a});b.set(b.k.af,!0)})}});
z.e.al=z.K(58,function(a,b){this.Ok=a;this.jd=b||this.jd;var c=this.Fd[a]=new z.vv;z.Su.C();var d=this.d.u.v(),f=(0,z.t)(this.ME,this,a),g=(0,z.t)(this.LE,this,a),h=this.d.M.Jm,d=d.get(z.U.Qc),h=z.w.nu(d,h)+String(a)+".json";z.Tu(0,h,f,g);return c});z.eG.prototype.al=z.K(57,function(a,b){this.Ck||(this.Ck=new LK(this.J));var c=this.Ck,d=KK(c,a,b);return c.al(d,a)});z.Su.prototype.Ph=z.K(49,function(a,b,c){a=z.wa("%s%scollection/%s/hot/",z.w.K.vd,z.w.Ye,a.na);(new z.Pe({url:a,wa:b,ra:c})).send()});
z.Qv.prototype.Ph=z.K(48,function(a){var b={na:this.d.u.v().id},c=z.Su.C().Ph;z.Rv(this,c,b,a);return a});z.eG.prototype.Ph=z.K(47,function(){z.Wv(this);this.Bi=new z.Qv(this.J,void 0);var a=new z.vv;this.Bi.Ph(a);return a});z.Su.prototype.Lh=z.K(46,function(a,b,c){a=z.wa("%s%scollection/%s/top/%s/",z.w.K.vd,z.w.Ye,a.na,a.RM);(new z.Pe({url:a,wa:b,ra:c})).send({format:"stream"})});z.Qv.prototype.Lh=z.K(45,function(a,b){var c={na:this.d.u.v().id,RM:a},d=z.Su.C().Lh;z.Rv(this,d,c,b);return b});
z.eG.prototype.Lh=z.K(44,function(a){z.Wv(this);this.Bi=new z.Qv(this.J,void 0);var b=new z.vv;this.Bi.Lh(a,b);return b});z.T.prototype.XF=z.K(43,function(){return this.aa});z.Bj.prototype.Tn=z.K(42,function(){return this.get(this.k.gp)});z.v(SK,z.zl);z.da(SK);var oL={fX:"attachmentDelegate"};z.kb(oL,z.sG);SK.prototype.Pn=function(a){var b=SK.b.Pn.call(this,a),c=a.attachmentDelegate;c&&(b.ZM=c);b.lx=a[oL.OK]||null;return b};z.v(TK,z.Gf);TK.prototype.send=function(a){this.vs=this.vs.concat(a)};TK.prototype.jy=function(){var a=VK(this.vs),a=UK(a);a.length&&this.RI.send(z.kd(a),{"Content-Type":"application/json"});this.vs=[]};TK.prototype.p=function(){(0,window.clearInterval)(this.Bc);this.RI=null;TK.b.p.call(this)};z.v(WK,z.Ej);WK.prototype.uy=function(a){this.wi=new z.Ou(this);this.Wt=new z.Gq(this,a);this.Ic=new z.yi(this);this.bb=new z.kv(this,a);this.Bl=new z.rv(this);this.u=new z.$u(this,a);this.Jb=new z.eG(this,a);new z.rf;this.Go=new z.gw(this,a);this.eW=new TK(this);this.Fb=new z.Ey(this)};z.v(XK,z.BF);z.e=XK.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.gx=b.v().fe();a.ST=!z.E.get(z.E.k.Pd);a.tl=b.tl(z.E.id);a.aO=2===c.get(z.U.wk);a.$N=3===c.get(z.U.wk);a.j={$S:z.X.get(z.X.g.yt),cT:z.X.get(z.X.g.zt),rS:z.X.get(z.X.g.uA),sx:z.X.get(z.X.g.Bp),tx:z.X.get(z.X.g.Cp),zo:z.X.get(z.X.g.xB),Qo:z.X.get(z.X.g.Fp),uW:z.X.get(z.X.g.PB)};return a};
z.e.G=function(a){XK.b.G.call(this,a);a=this.c;var b;b=this.s();var c=z.P,d=z.Qq(b),f;f=b.gx?(0,z.P)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.ST?b.tl?z.O(b.j.cT):z.O(b.j.$S):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(b.j.sx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(b.j.tx)+"\x3c/a\x3e"+(b.aO?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.O(b.j.uW)+"\x3c/a\x3e":"")+(b.$N?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.O(b.j.rS)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.$k=this.n("fyre-follow-conversation");this.Ps=this.n("fyre-stream-sort-hot-threads")||
null;this.Ky=this.n("fyre-stream-sort-top-comments")||null;this.rg=this.n("fyre-stream-sort-back");this.Yl=this.n("fyre-stream-sort-newest");this.Jy=this.n("fyre-stream-sort-oldest");this.QH=this.n("fyre-stream-sort-options");this.Zc=this.n("fyre-content-loading");this.Ad()};z.e.l=function(){XK.b.l.call(this);var a=this.q();z.E.on(z.E.xa.Lf,this.Jn,this);a.e(this.c,"click",this.hb);z.x([3,4,5],function(b){z.CF(this,a,b)},this);YK(this,a)};
z.e.hb=function(a){a.preventDefault();a=a.target;if(!z.Mo(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.rg)if(a===this.$k)this.KE();else switch(ZK(this,a),this.Xl(),a){case this.Ps:this.CD();break;case this.Ky:this.dispatchEvent({type:"sortTopComments",Tb:(0,z.t)(this.Ad,this)});break;case this.Yl:this.an("new");break;case this.Jy:this.an("old")}};z.e.ti=function(a,b){a&&this.vy(b);z.Hn(this.QH,"display",a?"none":"block");z.Hn(this.rg,"display",a?"block":"none")};
z.e.vy=function(a){var b=this.Yl,c=this.an,d=z.X.get(z.X.g.jt);4===a&&(b=this.Ps,c=this.CD,d=z.X.get(z.X.g.$I));this.rg.innerHTML=d;this.q().uf(this.rg,"click",(0,z.t)(function(a){a.stopPropagation();this.ti(!1);ZK(this,b);c.apply(this)},this))};z.e.Gn=function(a){a.stopPropagation();this.ti(!1);ZK(this,this.Yl);this.an()};z.e.mr=function(a){var b=a.Tb;z.kb(a,{Tb:(0,z.t)(function(){b();this.ti(!0,4)},this)})};
z.e.an=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Tb:(0,z.t)(this.Ad,this)})};z.e.CD=function(){this.dispatchEvent({type:"sortHotThreads",Tb:(0,z.t)(this.Ad,this)})};z.e.KE=function(){var a=this.d.u;a.v();var b=z.E.k;z.E.id?(b=a.tl(z.E.get(b.X)),a.nj(!b),a=b?z.X.get(z.X.g.yt):z.X.get(z.X.g.zt),this.$k.innerHTML=a):z.Qh(this.d.Ic,(0,z.t)(this.KE,this))};
z.e.Jn=function(){var a=this.d.u,b=a.v(),c=z.E.k,b=!b.fe()||z.E.get(c.Pd);this.$k&&(b?z.S(this.$k,!1):(a=a.tl(z.E.id)?z.X.get(z.X.g.zt):z.X.get(z.X.g.yt),this.$k.innerHTML=a,z.S(this.$k,!0)))};z.e.h=function(){XK.b.h.call(this);z.E.off(null,null,this)};z.v($K,XK);$K.prototype.G=function(a){this.c=a;z.Vl(a,QK,this.s());this.Yl=this.n("fyre-stream-sort-newest");this.Jy=this.n("fyre-stream-sort-oldest");this.QH=this.n("fyre-stream-sort-options");this.Zc=this.n("fyre-content-loading");this.Ad()};$K.prototype.an=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.gW.stream,direction:a,Tb:(0,z.t)(this.Ad,this)})};
$K.prototype.s=function(){return{j:{XM:z.X.get(z.X.g.VI),sx:z.X.get(z.X.g.Bp),tx:z.X.get(z.X.g.Cp),zo:z.X.get(z.X.g.xB),Qo:z.X.get(z.X.g.Fp)}}};z.v(aL,z.rx);z.e=aL.prototype;z.e.Rm=function(a){this.clear();z.S(this.c,!0);this.jd=a};z.e.clear=function(){this.gd.Hd();this.sb={};this.uj=[];for(this.lh=this.Fk=null;this.ma&&0!=this.ma.length;)this.po(0).p()};z.e.G=function(a){aL.b.G.call(this,a);z.Vl(this.c,z.Rq,this.s());this.Yj=this.n("fyre-stream-content");this.ui=this.n("fyre-stream-more");this.Fa.R(this.ui);z.S(this.ui,!1)};z.e.h=function(){this.Fa&&this.Fa.p();this.Fa=null;aL.b.h.call(this)};
z.e.l=function(){aL.b.l.call(this);this.q().e(this.Fa,"showMore",this.rw)};z.e.uv=function(){return this.J.M.LF};z.e.s=function(){return{Rc:z.w.K.kb,Nu:!!this.Fa,j:{By:z.X.get(z.X.g.WI)}}};z.e.sw=function(){this.Fa.Ls();this.Wg=!0};z.e.Lx=function(){this.dispatchEvent({type:this.Kt,direction:this.jd,target:this,IW:this.Wg&&this.LH,Tb:(0,z.t)(this.sw,this),mj:(0,z.t)(this.iF,this)});this.Wg&&(this.LH=!1)};z.e.Sx=function(a){this.Wg||aL.b.Sx.call(this,a)};
z.e.Fo=function(){var a=this.J.Jb.Ck,b=this.jd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.hp),c=!b&&a.Ok>-c;b&&-1>a.Ok||c?this.Fa.show():this.Fa.nb()};z.e.start=function(){this.Wg||this.Lx()};z.v(bL,z.yF);var pL=z.X.g,qL={};qL.comment=[pL.zm,pL.Mf,pL.mm];qL.liveblog=[pL.pL,pL.CK,pL.AA];bL.prototype.hE=function(a){function b(a){return z.Ga(a,"%s")?a:"%s "+a}var c=this.m.fe()?"liveblog":"comment",c=qL[c];switch(a){case 1:c=b(z.X.get(c[1]));break;case 0:if(z.X.get(c[0])!==z.uG[c[0]]){c=z.X.get(c[0]);break}default:c=b(z.X.get(c[2]))}return z.wa(c,a)};z.v(cL,z.Tt);cL.prototype.Io=200;cL.prototype.Rh=function(){return new dL(this.Hc)};cL.prototype.s=function(){var a={};a.message=this.dz;return a};z.v(dL,z.Nt);dL.prototype.Mc=function(a,b,c){var d=z.go(this.element),d=new z.Ah(d.width,d.height+25);b=z.It(this.element,this.Bh,a,b,d,c,9);z.Nn(a.lastChild,0);b&&(d=new z.Ah(0,-5),z.It(this.element,2,a,1,d,c,5),z.Nn(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.v(eL,z.T);z.e=eL.prototype;z.e.r=function(){this.c=z.Yl(PK,this.s())};z.e.l=function(){eL.b.l.call(this);this.Sa=new cL(this.c,this.m.get("displayName"));this.q().e(this.c,"click",this.hb)};z.e.h=function(){eL.b.h.call(this);this.Sa&&this.Sa.p()};z.e.s=function(){var a=z.Wd,b={};b.ud=this.m.get(a.ub);b.Yb=this.m.get(a.kk);b.Z=this.m.get(a.ua);b.id=this.m.id;b.tS=this.m.id.replace(/[@.]/g,"-");b.Da=this.m.get(a.Vb);return b};
z.e.hb=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.m,type:"author_click"})};z.v(fL,z.T);z.e=fL.prototype;z.e.EA=10;z.e.h=function(){fL.b.h.call(this);delete this.bc};z.e.Q=function(){fL.b.Q.call(this);this.bc.off(null,null,this)};z.e.uE=function(a){a=new eL(a);var b=this.Lc();if(b===this.EA){var c=this.po(b-1);c&&(c.p(),b--)}0<b?this.xe(a,0,!0):this.D(a,!0)};z.e.xR=function(a){var b;this.Tc(function(c){a.id===c.m.id&&(b=c)});b&&(this.removeChild(b),b.p())};
z.e.Xh=function(){this.bc.on(this.bc.xa.ht,this.uE,this);this.bc.on(this.bc.xa.Ht,this.xR,this);var a=this.bc.ob.reverse().slice(0,this.EA);z.x(a,this.uE,this)};z.v(gL,fL);z.v(iL,z.JF);
iL.prototype.iH=function(a,b){if(!this.Ia){this.B=b;var c=b.get(z.U.uh),d=b.get(z.U.Qd);this.bt=new z.GF(c,d,a.M.Ua);this.D(this.bt);this.kq=new bL(a.u.v());this.D(this.kq);this.Yr=null;b.Tn()&&(this.gu=new $K(a),this.D(this.gu),this.Dk=new aL(a),this.D(this.Dk),MK(this.gu,{stream:this.Dk}));this.ih=new XK(a);this.D(this.ih);this.Qr((0,z.t)(function(a){this.Zb=a;this.D(this.Zb);a=this.Zb;this.aa&&a&&a.R(this.Ce,!0)},this));b.get(z.U.sm)&&!z.cg&&NK(this.B)&&(this.B.Xg()||this.B.fe()||this.Wv())}};
iL.prototype.s=function(){var a=!this.d.M.aq&&!z.w.Lu&&!this.d.M.yD;return{lI:z.w.K.ez,mI:(0,window.encodeURIComponent)(String(window.location.href)),Ua:this.d.M.Ua,Xg:this.B.Xg(),fe:this.B.fe(),ge:z.cg,Uu:a,KS:this.d.M.aq,Tn:this.B.Tn()}};z.Fx={bX:"fyre-archive-stream",cX:"fyre-archive-stream-header",O_:"fyre-top-content-stream",g0:"fyre-widget",sm:"fyre-featured-content-wrapper"};z.kb(z.Fx,z.vJ);z.e=iL.prototype;
z.e.r=function(){this.c=z.Yl(OK,this.s());var a=this.B.get(z.U.wk);if(1!==a){var b=this.d.Fb,a=2===a?3:4,c=this.n("fyre-top-content-stream");z.Fy(b,a,c,this)}this.tr.R(this.n(z.Fx.nK));this.Dk&&(b=this.n("fyre-archive-stream-header"),this.gu.R(b),this.Dk.R(this.n("fyre-archive-stream")));this.Ch(1);this.Ce=this.n(z.Fx.sh);b=jL(this);z.S(this.Ce,b)};
z.e.l=function(){iL.b.l.call(this);var a=this.Zb;this.aa&&a&&a.R(this.Ce,!0);this.d.T.So("stream_data_received",this.vQ,this);this.q().e(this,"request_content_context",this.WP).e(this,"request_content_reply",this.AR);this.Dk&&this.Dk.start()};z.e.Xh=function(){this.mn&&this.mn.Xh();this.fg.Xh()};z.e.vQ=function(){var a=this.B,b=a.get(z.U.nk);z.rh||b||(b=(0,z.t)(function(){this.Yr=new z.rL(this.d,a.get(z.U.Qd));this.D(this.Yr,!0)},this),z.uc(z.w.K.kb+z.w.xf.Yr,null,null,b))};
z.e.Wv=function(){var a=new z.qE(this.XF,this);a.LG=(0,z.t)(this.hV,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);z.uc(z.w.K.kb+z.w.xf.HO,null,null,b)};z.e.hV=function(){var a=this.n("fyre-featured-content-wrapper");this.gv=new z.LJ(this.d);this.D(this.gv);this.gv.R(a);this.gv.Vg()};z.e.Qr=function(a){if(!this.d.M.readOnly){var b=this.d.u.v();z.Bw(z.yw.C(),"main",a,{J:this.d,mi:"new"},b);z.E.on(z.E.gc(z.E.k.X),this.Vc,this)}};z.e.Vc=function(){var a=jL(this);z.S(this.Ce,a)};
z.e.Wh=function(){0<z.xo(this,this.Zb)&&(this.removeChild(this.Zb),this.Zb.p());this.Qr((0,z.t)(function(a){this.Zb=a;this.D(this.Zb);a=this.Zb;this.aa&&a&&a.R(this.Ce,!0);z.S(this.Ce,!0)},this))};z.e.Tg=function(a){null!=a&&(this.d.Fb.gl(1),(0,window.setTimeout)((0,z.t)(function(){this.Ia||z.KF(this,a)},this),3E3))};z.e.WP=function(a){z.KF(this,a.Jk)};z.e.AR=function(a){z.KF(this,a.Jk,function(a){z.xw(a.Ib)})};
z.e.h=function(){iL.b.h.call(this);z.E.off(z.E.gc(z.E.k.X),this.Vc,this);this.B&&(this.B.off(null,null,this),this.B=null)};z.v(kL,z.Uy);z.e=kL.prototype;z.e.ce=function(a,b){kL.b.ce.call(this,a,b);a.e(b,"repliesExpanded",this.HE);a.e(b,"sortHotThreads",this.KR);a.e(b,"sortOrderChanged",this.lF);a.e(b,"sortTopComments",this.LR);a.e(b,"archiveShowMore",this.HP);a.e(b,"archiveSortOrderChanged",this.IP)};
z.e.HP=function(a){var b=a.Tb||z.n,c=(0,z.t)(this.He,this,a.target),d=this.d.Jb;a=a.IW;d.Ck||(d.Ck=new LK(d.J));d=d.Ck;a=a?d.Ok:KK(d);var f=d.me[a];f&&(d.Ok=a);if(f)b(),c(f);else{d=this.d.Jb.al();a=d.k.af;if(d.get(a))b();else d.on(d.gc(a),b,this);z.Vy(this,d,c)}};z.e.Rv=function(a,b){var c=2===b.$c,d=1!==b.$c;switch(b.type){case 0:var f=this.d.u.v(),f=z.tk(b,f),g=f.get(z.Gk),g=this.d.u.ab().get(g);f.set(z.uk,g);a.iw(f,c,d)}};
z.e.dF=function(a){if(1!==this.Fm){var b=this.ZV.ih;b.ti(!1);ZK(b,b.Yl);z.kb(a,{direction:"new",Tb:z.n});this.lF(a)}};z.e.IP=function(a){z.Wy(this);a.stream.Rm(a.direction);var b=this.d.Jb.al(a.direction,!0),c=(0,z.t)(function(b){a.Tb();this.He(a.stream,b)},this);z.Vy(this,b,c,a.mj)};z.e.lF=function(a){this.d.M.Qn=null;var b=z.Yy(this,1);z.Wv(this.d.Jb);b.Rm(a.direction);var c=z.Vv(this.d.Jb,a.direction),d=(0,z.t)(function(c){a.Tb();this.He(b,c)},this);z.Vy(this,c,d,a.mj)};
z.e.LR=function(a){var b=z.Yy(this,3),c=this.d.Jb.Lh("likes");z.Vy(this,c,(0,z.t)(function(c){a.Tb();z.hb(c)?z.qx(b):this.He(b,c)},this))};z.e.KR=function(a){var b=z.Yy(this,4),c=this.d.Jb.Ph();z.Vy(this,c,(0,z.t)(function(c){a.Tb();z.hb(c)?z.qx(b):this.He(b,c)},this))};z.v(lL,z.Is);z.e=lL.prototype;z.e.c=null;z.e.h=function(){lL.b.h.call(this);this.Rs.p();this.TC.p();this.Pb.aa&&this.Pb.p();this.Kf&&this.Kf.p();delete this.Kf};z.e.pl=function(a){lL.b.pl.call(this,a);this.Rs=new kL(this.d);this.Rs.handle(a);this.TC=new z.Ty(this.d);this.TC.handle(a)};z.e.Ry=function(){this.d.wi.stop()};z.e.fW=function(){this.d.Bl.stop()};z.e.Vj=function(){this.d.wi.start()};z.e.bW=function(){this.d.Bl.start()};
z.e.oa=function(){this.Kf&&this.Kf.p();this.Pb.oa(this.c);if("object"===typeof window.Livefyre&&window.Livefyre.KM)z.Ns(this);else{var a=z.Ks(this);this.Pb.Tg(a)}this.d.T.N("render_complete")};z.v(mL,z.tl);mL.prototype.jC=SK.C();mL.prototype.h=function(){mL.b.h.call(this);this.stop();delete this.M;delete this.ha;nL(this);z.yl(this);this.lj&&(this.lj.p(),delete this.lj)};mL.prototype.Zy=function(){this.stop();nL(this);mL.b.Zy.call(this)};z.lg.main.Eh.ia(mL);})(fyre.conv);
